#!/usr/bin/env python3
"""Generate aisp.hook/fake_vtables.inc: for each COM interface the synthesized document
implements, a FillStubs() that points every vtable slot at an E_NOTIMPL stub of the right
signature, so the slots the hook does not implement are still safe to call (stdcall pops its
own arguments, so every slot needs a stub of its exact arity). Reads the MinGW headers:

    ./scripts/gen-fake-vtables.py /usr/i686-w64-mingw32/include > aisp.hook/fake_vtables.inc
"""
import re
import sys

INTERFACES = ["IHTMLDocument2", "IHTMLDocument3", "IHTMLWindow2", "IHTMLElement", "IViewObject2"]


def members(src, name):
    match = re.search(r"typedef struct %sVtbl \{(.*?)\n\} %sVtbl;" % (name, name), src, re.S)
    if not match:
        raise SystemExit("no vtable struct for " + name)
    out, depth, cur = [], 0, ""
    for ch in match.group(1):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == ";" and depth == 0:
            found = re.search(r"\(STDMETHODCALLTYPE \*(\w+)\)", cur)
            if found:
                out.append(found.group(1))
            cur = ""
        else:
            cur += ch
    return out


def main():
    include = sys.argv[1] if len(sys.argv) > 1 else "/usr/i686-w64-mingw32/include"
    src = ""
    for header in ("mshtml.h", "oleidl.h", "oaidl.h"):
        with open("%s/%s" % (include, header), encoding="utf-8", errors="replace") as f:
            src += f.read()
    print("// Generated by scripts/gen-fake-vtables.py from the MinGW SDK headers; do not edit.")
    print("// Every slot gets an E_NOTIMPL stub of its own signature; document.cpp overrides the ones it implements.")
    for name in INTERFACES:
        print("\ninline void FillStubs(%sVtbl& vt)\n{" % name)
        for member in members(src, name):
            print("    vt.%s = Stub<decltype(%sVtbl::%s)>::fn;" % (member, name, member))
        print("}")


if __name__ == "__main__":
    main()
